### ISSUE TITLE
error with react@16.0.0

### ISSUE THREAD

**Issue by ldk18501** [cassiozen/react-simple-dnd#1]
`children: React__default.PropTypes.oneOfType([React__default.PropTypes.func, React__default.PropTypes.element]).isRequired`
this syntax will cause 
`Uncaught TypeError: Cannot read property 'oneOfType' of undefined`
while using react@16.0.0

hope this can be fixed

**Comment by hsluoyz** [comment]
Same error. Not fixed.

**Comment by konsumer** [comment]
Also same error, not fixed. Why was this closed?
